### ISSUE TITLE
"strict": true not respected

### ISSUE THREAD

**Issue by monoclex** [janjakubnanista/ts-type-checked#43]
Given some code

```ts
import { isA } from "ts-type-checked";

console.log(isA<string>(null));
console.log(isA<string>(undefined));
```

`true` is outputted. This should be `false`, especially if `strict: true` is set in the `tsconfig.json`.

**Comment by janjakubnanista** [comment]
Hey @SirJosh3917! Thanks for submitting an issue!

Could you provide me with you `tsconfig.json`? I need that to debug the issue. Thanks!

**Comment by janjakubnanista** [comment]
Closed due to inactivity. Please reopen if needed.

**Comment by abrenneke** [comment]
@janjakubnanista looks what happens is that `--strict` implies `--strictNullChecks`, but it looks like ts-type-checked doesn't know that, and assumes strictNullChecks is off, so generates not-very-useful code.

Right now, `"strictNullChecks": true` needs to be added explicitly to the tsconfig.json file, even though it should be implied by `"strict": true`.

So yeah please reopen!

**Comment by janjakubnanista** [comment]
Aaaah I see. Easy fix then! Will publish a new version soon. Thanks @abrenneke!

**Comment by janjakubnanista** [comment]
The fix is now merged, will close the issue once it's published on NPM!
