### ISSUE TITLE
Optional boolean causes error

### ISSUE THREAD

**Issue by loicnestler** [janjakubnanista/ts-type-checked#79]
Hey there!

So my issue is the following:

This type:
```typescript
type FieldOptions = {
   label?: string
   description?: string
   repeat?: boolean
}
```
when used in the `isA` function throws the following error
```typescript
    !isA<FieldOptions>(options) // ...
```
```
/Users/loic/Documents/xxx/projects/yyy/node_modules/typescript/lib/typescript.js:110417
                throw e;
                ^

Error: Could not find value for a literal type false
```

However neither does this type
```typescript
type FieldOptions = {
   label?: string
   description?: string
   repeat: boolean
}
```
nor this one
```typescript
type FieldOptions = {
   label?: string
   description?: string
   repeat?: number
}
```

throw the same error. The last two types just work and compile fine.

Is there any way around that? Or any reason for why this is happening, so I can take a dive into the code myself?

Thanks in regards!

**Comment by janjakubnanista** [comment]
Fixed in `0.6.5`! Sorry for the long wait
